all:
  children:
    my_servers:
      hosts:
        my_ubuntu:
          ansible_host: 194.87.253.126

all:
  hosts:
    mail.example.com:
  children:
    webservers:
      hosts:
        foo.example.com:
        bar.example.com:
    dbservers:
      hosts:
        one.example.com:
        two.example.com:
        three.example.com: